In [1]:
import pandas as pd 
import os 
from skimage.transform import resize 
from skimage.io import imread 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn import svm 
from sklearn.model_selection import GridSearchCV 
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
color = ['rgb_b','rgb_g','rgb_r']#,'hsv_h','hsv_s','hsv_v','yuv_y','yuv_u','yuv_v','lab_l','lab_a','lab_b']

In [3]:
for c in color:
    Categories=['nevus','melanoma','seborrheic_keratosis'] 
    flat_data_arr=[] #input array 
    target_arr=[] #output array 
    datadir='E:/melanoma/channels/'+str(c)+'/train' 
    #path which contains all the categories of images 
    for i in Categories: 
        print(f'loading... category : {i}') 
        path=os.path.join(datadir,i) 
        for img in os.listdir(path): 
            img_array=imread(os.path.join(path,img)) 
            img_resized=resize(img_array,(150,100,1)) 
            flat_data_arr.append(img_resized.flatten()) 
            target_arr.append(Categories.index(i)) 
        print(f'loaded category:{i} successfully') 
    flat_data=np.array(flat_data_arr) 
    target=np.array(target_arr)

    #dataframe 
    df=pd.DataFrame(flat_data) 
    df['Target']=target 
    df.shape

    #input data 
    x_train=df.iloc[:,:-1] 
    #output data 
    y_train=df.iloc[:,-1]

    Categories=['nevus','melanoma','seborrheic_keratosis'] 
    flat_data_arr=[] #input array 
    target_arr=[] #output array 
    datadir='E:/melanoma/channels/hsv_h/test' 
    #path which contains all the categories of images 
    for i in Categories: 
        print(f'loading... category : {i}') 
        path=os.path.join(datadir,i) 
        for img in os.listdir(path): 
            img_array=imread(os.path.join(path,img)) 
            img_resized=resize(img_array,(150,100,1)) 
            flat_data_arr.append(img_resized.flatten()) 
            target_arr.append(Categories.index(i)) 
        print(f'loaded category:{i} successfully') 
    flat_data=np.array(flat_data_arr) 
    target=np.array(target_arr)

    #dataframe 
    df=pd.DataFrame(flat_data) 
    df['Target']=target 
    df.shape

    #input data 
    x_test=df.iloc[:,:-1] 
    #output data 
    y_test=df.iloc[:,-1]

    # Creating a support vector classifier 
    svc=svm.SVC(probability=True, kernel='poly', C=0.1, gamma=0.001) 

    # Training the model using the training data 
    svc.fit(x_train,y_train)

    # Testing the model using the testing data 
    y_pred = svc.predict(x_test) 

    # Calculating the accuracy of the model 
    accuracy_svc = accuracy_score(y_pred, y_test) 

    # Print the accuracy of the model 
    print(f"The model is {accuracy_svc*100}% accurate")

    classification_svc = classification_report(y_test, y_pred, target_names=['nevus','melanoma','seborrheic_keratosis'] )
    confusion_matrix_svc = confusion_matrix(y_test,y_pred)
    print(confusion_matrix_svc)
    print(classification_svc)

    # obiekt klasyfikatora – liczba drzew i inne hiperparametry do optymalizacji
    clf = RandomForestClassifier(n_estimators=10, random_state=10)
    clf.fit(x_train, y_train) # trenowanie klasyfikatora
    y_test_pred = clf.predict(x_test)
    # dokładność dla zbioru testowego
    print('\nAccuracy (test):', accuracy_score(y_test, y_test_pred))

    # Macierz pomyłek i raport z klasyfikacji
    classification_rf = classification_report(y_test,y_test_pred,target_names=['nevus','melanoma','seborrheic_keratosis'])
    confusion_matrix_rf = confusion_matrix(y_test,y_test_pred)
    print(confusion_matrix_rf)
    print(classification_rf)

loading... category : nevus
loaded category:nevus successfully
loading... category : melanoma
loaded category:melanoma successfully
loading... category : seborrheic_keratosis
loaded category:seborrheic_keratosis successfully
loading... category : nevus
loaded category:nevus successfully
loading... category : melanoma
loaded category:melanoma successfully
loading... category : seborrheic_keratosis
loaded category:seborrheic_keratosis successfully
The model is 65.5% accurate
[[393   0   0]
 [117   0   0]
 [ 90   0   0]]
                      precision    recall  f1-score   support

               nevus       0.66      1.00      0.79       393
            melanoma       0.00      0.00      0.00       117
seborrheic_keratosis       0.00      0.00      0.00        90

            accuracy                           0.66       600
           macro avg       0.22      0.33      0.26       600
        weighted avg       0.43      0.66      0.52       600



c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Accuracy (test): 0.42333333333333334
[[215 165  13]
 [ 77  39   1]
 [ 75  15   0]]
                      precision    recall  f1-score   support

               nevus       0.59      0.55      0.57       393
            melanoma       0.18      0.33      0.23       117
seborrheic_keratosis       0.00      0.00      0.00        90

            accuracy                           0.42       600
           macro avg       0.25      0.29      0.27       600
        weighted avg       0.42      0.42      0.42       600

loading... category : nevus
loaded category:nevus successfully
loading... category : melanoma
loaded category:melanoma successfully
loading... category : seborrheic_keratosis
loaded category:seborrheic_keratosis successfully
loading... category : nevus
loaded category:nevus successfully
loading... category : melanoma
loaded category:melanoma successfully
loading... category : seborrheic_keratosis
loaded category:seborrheic_keratosis successfully
The model is 68.0% accurate
[

In [4]:
color = ['hsv_h','hsv_s','hsv_v','yuv_y','yuv_u','yuv_v','lab_l','lab_a','lab_b']

In [5]:
for c in color:
    Categories=['nevus','melanoma','seborrheic_keratosis'] 
    flat_data_arr=[] #input array 
    target_arr=[] #output array 
    datadir='E:/melanoma/channels/'+str(c)+'/train' 
    #path which contains all the categories of images 
    for i in Categories: 
        print(f'loading... category : {i}') 
        path=os.path.join(datadir,i) 
        for img in os.listdir(path): 
            img_array=imread(os.path.join(path,img)) 
            img_resized=resize(img_array,(150,100,1)) 
            flat_data_arr.append(img_resized.flatten()) 
            target_arr.append(Categories.index(i)) 
        print(f'loaded category:{i} successfully') 
    flat_data=np.array(flat_data_arr) 
    target=np.array(target_arr)

    #dataframe 
    df=pd.DataFrame(flat_data) 
    df['Target']=target 
    df.shape

    #input data 
    x_train=df.iloc[:,:-1] 
    #output data 
    y_train=df.iloc[:,-1]

    Categories=['nevus','melanoma','seborrheic_keratosis'] 
    flat_data_arr=[] #input array 
    target_arr=[] #output array 
    datadir='E:/melanoma/channels/hsv_h/test' 
    #path which contains all the categories of images 
    for i in Categories: 
        print(f'loading... category : {i}') 
        path=os.path.join(datadir,i) 
        for img in os.listdir(path): 
            img_array=imread(os.path.join(path,img)) 
            img_resized=resize(img_array,(150,100,1)) 
            flat_data_arr.append(img_resized.flatten()) 
            target_arr.append(Categories.index(i)) 
        print(f'loaded category:{i} successfully') 
    flat_data=np.array(flat_data_arr) 
    target=np.array(target_arr)

    #dataframe 
    df=pd.DataFrame(flat_data) 
    df['Target']=target 
    df.shape

    #input data 
    x_test=df.iloc[:,:-1] 
    #output data 
    y_test=df.iloc[:,-1]

    # Creating a support vector classifier 
    svc=svm.SVC(probability=True, kernel='poly', C=0.1, gamma=0.001) 

    # Training the model using the training data 
    svc.fit(x_train,y_train)

    # Testing the model using the testing data 
    y_pred = svc.predict(x_test) 

    # Calculating the accuracy of the model 
    accuracy_svc = accuracy_score(y_pred, y_test) 

    # Print the accuracy of the model 
    print(f"The model is {accuracy_svc*100}% accurate")

    classification_svc = classification_report(y_test, y_pred, target_names=['nevus','melanoma','seborrheic_keratosis'] )
    confusion_matrix_svc = confusion_matrix(y_test,y_pred)
    print(confusion_matrix_svc)
    print(classification_svc)

    # obiekt klasyfikatora – liczba drzew i inne hiperparametry do optymalizacji
    clf = RandomForestClassifier(n_estimators=10, random_state=10)
    clf.fit(x_train, y_train) # trenowanie klasyfikatora
    y_test_pred = clf.predict(x_test)
    # dokładność dla zbioru testowego
    print('\nAccuracy (test):', accuracy_score(y_test, y_test_pred))

    # Macierz pomyłek i raport z klasyfikacji
    classification_rf = classification_report(y_test,y_test_pred,target_names=['nevus','melanoma','seborrheic_keratosis'])
    confusion_matrix_rf = confusion_matrix(y_test,y_test_pred)
    print(confusion_matrix_rf)
    print(classification_rf)

loading... category : nevus
loaded category:nevus successfully
loading... category : melanoma
loaded category:melanoma successfully
loading... category : seborrheic_keratosis
loaded category:seborrheic_keratosis successfully
loading... category : nevus
loaded category:nevus successfully
loading... category : melanoma
loaded category:melanoma successfully
loading... category : seborrheic_keratosis
loaded category:seborrheic_keratosis successfully
The model is 68.33333333333333% accurate
[[388   5   0]
 [113   4   0]
 [ 72   0  18]]
                      precision    recall  f1-score   support

               nevus       0.68      0.99      0.80       393
            melanoma       0.44      0.03      0.06       117
seborrheic_keratosis       1.00      0.20      0.33        90

            accuracy                           0.68       600
           macro avg       0.71      0.41      0.40       600
        weighted avg       0.68      0.68      0.59       600


Accuracy (test): 0.641666

c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Accuracy (test): 0.5016666666666667
[[244 140   9]
 [ 55  57   5]
 [ 40  50   0]]
                      precision    recall  f1-score   support

               nevus       0.72      0.62      0.67       393
            melanoma       0.23      0.49      0.31       117
seborrheic_keratosis       0.00      0.00      0.00        90

            accuracy                           0.50       600
           macro avg       0.32      0.37      0.33       600
        weighted avg       0.52      0.50      0.50       600

loading... category : nevus
loaded category:nevus successfully
loading... category : melanoma
loaded category:melanoma successfully
loading... category : seborrheic_keratosis
loaded category:seborrheic_keratosis successfully
loading... category : nevus
loaded category:nevus successfully
loading... category : melanoma
loaded category:melanoma successfully
loading... category : seborrheic_keratosis
loaded category:seborrheic_keratosis successfully
The model is 68.16666666666666

c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Accuracy (test): 0.59
[[338  55   0]
 [101  16   0]
 [ 87   3   0]]
                      precision    recall  f1-score   support

               nevus       0.64      0.86      0.74       393
            melanoma       0.22      0.14      0.17       117
seborrheic_keratosis       0.00      0.00      0.00        90

            accuracy                           0.59       600
           macro avg       0.29      0.33      0.30       600
        weighted avg       0.46      0.59      0.51       600

loading... category : nevus


c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


loaded category:nevus successfully
loading... category : melanoma
loaded category:melanoma successfully
loading... category : seborrheic_keratosis
loaded category:seborrheic_keratosis successfully
loading... category : nevus
loaded category:nevus successfully
loading... category : melanoma
loaded category:melanoma successfully
loading... category : seborrheic_keratosis
loaded category:seborrheic_keratosis successfully
The model is 65.5% accurate
[[393   0   0]
 [117   0   0]
 [ 90   0   0]]
                      precision    recall  f1-score   support

               nevus       0.66      1.00      0.79       393
            melanoma       0.00      0.00      0.00       117
seborrheic_keratosis       0.00      0.00      0.00        90

            accuracy                           0.66       600
           macro avg       0.22      0.33      0.26       600
        weighted avg       0.43      0.66      0.52       600



c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Accuracy (test): 0.37166666666666665
[[169 166  58]
 [ 58  46  13]
 [ 48  34   8]]
                      precision    recall  f1-score   support

               nevus       0.61      0.43      0.51       393
            melanoma       0.19      0.39      0.25       117
seborrheic_keratosis       0.10      0.09      0.09        90

            accuracy                           0.37       600
           macro avg       0.30      0.30      0.28       600
        weighted avg       0.45      0.37      0.40       600

loading... category : nevus
loaded category:nevus successfully
loading... category : melanoma
loaded category:melanoma successfully
loading... category : seborrheic_keratosis
loaded category:seborrheic_keratosis successfully
loading... category : nevus
loaded category:nevus successfully
loading... category : melanoma
loaded category:melanoma successfully
loading... category : seborrheic_keratosis
loaded category:seborrheic_keratosis successfully
The model is 68.0% accurate
[

c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\Programs\envs\gollum\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Accuracy (test): 0.285
[[108 222  63]
 [ 49  54  14]
 [ 37  44   9]]
                      precision    recall  f1-score   support

               nevus       0.56      0.27      0.37       393
            melanoma       0.17      0.46      0.25       117
seborrheic_keratosis       0.10      0.10      0.10        90

            accuracy                           0.28       600
           macro avg       0.28      0.28      0.24       600
        weighted avg       0.41      0.28      0.30       600

